// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGy9AK3C_6tEjSZx5po-UbcBJ4KO_60w',
    appId: '1:518021439110:web:c1732cf1c62e96df053b07',
    messagingSenderId: '518021439110',
    projectId: 'ebay-login-demo',
    authDomain: 'ebay-login-demo.firebaseapp.com',
    storageBucket: 'ebay-login-demo.firebasestorage.app',
    measurementId: 'G-3MFE64VSL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8-qEdg4T1fIrwU4B0CGhMQbPmMgV_7Y',
    appId: '1:518021439110:android:b318fc18f530e007053b07',
    messagingSenderId: '518021439110',
    projectId: 'ebay-login-demo',
    storageBucket: 'ebay-login-demo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt47T2pO9MT-PClH2cX3jcpsJr1VC82OU',
    appId: '1:518021439110:ios:b960b704427b1ed5053b07',
    messagingSenderId: '518021439110',
    projectId: 'ebay-login-demo',
    storageBucket: 'ebay-login-demo.firebasestorage.app',
    iosBundleId: 'com.example.ebay',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt47T2pO9MT-PClH2cX3jcpsJr1VC82OU',
    appId: '1:518021439110:ios:b960b704427b1ed5053b07',
    messagingSenderId: '518021439110',
    projectId: 'ebay-login-demo',
    storageBucket: 'ebay-login-demo.firebasestorage.app',
    iosBundleId: 'com.example.ebay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGy9AK3C_6tEjSZx5po-UbcBJ4KO_60w',
    appId: '1:518021439110:web:bedf3c8fac4b6347053b07',
    messagingSenderId: '518021439110',
    projectId: 'ebay-login-demo',
    authDomain: 'ebay-login-demo.firebaseapp.com',
    storageBucket: 'ebay-login-demo.firebasestorage.app',
    measurementId: 'G-X1V6M6CX58',
  );
}
