// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATc_nV0l4YFDJ0OzHBdQeVl37dS3hSC0o',
    appId: '1:960742375625:web:9cf9736c729a0708c04d18',
    messagingSenderId: '960742375625',
    projectId: 'facebook-login-demo-fb256',
    authDomain: 'facebook-login-demo-fb256.firebaseapp.com',
    storageBucket: 'facebook-login-demo-fb256.firebasestorage.app',
    measurementId: 'G-BGE231DBKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtC12e7InOSMYNGxUXe47plIzwHr2vww',
    appId: '1:960742375625:android:532e0ec14e70d559c04d18',
    messagingSenderId: '960742375625',
    projectId: 'facebook-login-demo-fb256',
    storageBucket: 'facebook-login-demo-fb256.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPGi40vP39Jw-6Uu4Ffp7V71myM7lxsU',
    appId: '1:960742375625:ios:27c42c1a68746e29c04d18',
    messagingSenderId: '960742375625',
    projectId: 'facebook-login-demo-fb256',
    storageBucket: 'facebook-login-demo-fb256.firebasestorage.app',
    iosBundleId: 'com.example.facebookLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPGi40vP39Jw-6Uu4Ffp7V71myM7lxsU',
    appId: '1:960742375625:ios:27c42c1a68746e29c04d18',
    messagingSenderId: '960742375625',
    projectId: 'facebook-login-demo-fb256',
    storageBucket: 'facebook-login-demo-fb256.firebasestorage.app',
    iosBundleId: 'com.example.facebookLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATc_nV0l4YFDJ0OzHBdQeVl37dS3hSC0o',
    appId: '1:960742375625:web:1b95eabf88b3aa25c04d18',
    messagingSenderId: '960742375625',
    projectId: 'facebook-login-demo-fb256',
    authDomain: 'facebook-login-demo-fb256.firebaseapp.com',
    storageBucket: 'facebook-login-demo-fb256.firebasestorage.app',
    measurementId: 'G-BT7TL45K5V',
  );
}
