// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6-bZGQ1pH5SP5kdy1qzSRTPYgRsIVqA',
    appId: '1:1011411124387:web:a6b8a3bbb9de1ee6c0bf16',
    messagingSenderId: '1011411124387',
    projectId: 'instagram-login-demo-37662',
    authDomain: 'instagram-login-demo-37662.firebaseapp.com',
    storageBucket: 'instagram-login-demo-37662.firebasestorage.app',
    measurementId: 'G-MN6DF27R3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4a_-NiqV-HFr0AKiqn-SaM2jwIXmHyI',
    appId: '1:1011411124387:android:0797d999999928a3c0bf16',
    messagingSenderId: '1011411124387',
    projectId: 'instagram-login-demo-37662',
    storageBucket: 'instagram-login-demo-37662.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZ0MeQ9iCsVjm8kKE6nnvyZP31neT6dE',
    appId: '1:1011411124387:ios:35bc0cdbc5fa4521c0bf16',
    messagingSenderId: '1011411124387',
    projectId: 'instagram-login-demo-37662',
    storageBucket: 'instagram-login-demo-37662.firebasestorage.app',
    iosBundleId: 'com.example.instagramLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZ0MeQ9iCsVjm8kKE6nnvyZP31neT6dE',
    appId: '1:1011411124387:ios:35bc0cdbc5fa4521c0bf16',
    messagingSenderId: '1011411124387',
    projectId: 'instagram-login-demo-37662',
    storageBucket: 'instagram-login-demo-37662.firebasestorage.app',
    iosBundleId: 'com.example.instagramLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh6-bZGQ1pH5SP5kdy1qzSRTPYgRsIVqA',
    appId: '1:1011411124387:web:8ac0b2ce80e0d146c0bf16',
    messagingSenderId: '1011411124387',
    projectId: 'instagram-login-demo-37662',
    authDomain: 'instagram-login-demo-37662.firebaseapp.com',
    storageBucket: 'instagram-login-demo-37662.firebasestorage.app',
    measurementId: 'G-J5LJ2EEB1B',
  );
}
