// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// NOTE: This file is a placeholder with dummy configurations so the app compiles cleanly.
/// To connect to your real Firebase project:
/// 1. Run `flutterfire configure` in this project directory.
/// 2. It will overwrite this file with your project's real Firebase keys.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnZPyq_nAYu3mdd9JNreAOdKig4cHgIE',
    appId: '1:499763437222:web:77cfadd4661687fb891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    authDomain: 'flutter-auth-a8d16.firebaseapp.com',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    measurementId: 'G-T12ZCE9VXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFxzUrBpqjMO5VUOM1-kr3px3I9_PYAI',
    appId: '1:499763437222:android:4a41ddfb7d19b433891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYp2lmgWJcJbB81kxa3nKGAGV9J6KhXpI',
    appId: '1:499763437222:ios:fe216bd863a0be9c891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    iosClientId: '499763437222-0404u2pt6eljblctngvlacj17ngm2utq.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYp2lmgWJcJbB81kxa3nKGAGV9J6KhXpI',
    appId: '1:499763437222:ios:fe216bd863a0be9c891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    iosClientId: '499763437222-0404u2pt6eljblctngvlacj17ngm2utq.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJnZPyq_nAYu3mdd9JNreAOdKig4cHgIE',
    appId: '1:499763437222:web:77cfadd4661687fb891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    authDomain: 'flutter-auth-a8d16.firebaseapp.com',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    measurementId: 'G-T12ZCE9VXL',
  );
}
