// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcRWIfYLASO9aYmgbkKa6TafIQh07ec4',
    appId: '1:121984401432:web:f50a5fd4e5deb7562bc36d',
    messagingSenderId: '121984401432',
    projectId: 'ludo-game-login-demo',
    authDomain: 'ludo-game-login-demo.firebaseapp.com',
    storageBucket: 'ludo-game-login-demo.firebasestorage.app',
    measurementId: 'G-65CF70ZHCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYnn-DTzTTfIJqZnFGO3SPskKj6tna5us',
    appId: '1:121984401432:android:90917a1d4f2b11872bc36d',
    messagingSenderId: '121984401432',
    projectId: 'ludo-game-login-demo',
    storageBucket: 'ludo-game-login-demo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChiYTw5rKmP-ioG__X30GQgbAxwujxVvw',
    appId: '1:121984401432:ios:4739e656de7c58a92bc36d',
    messagingSenderId: '121984401432',
    projectId: 'ludo-game-login-demo',
    storageBucket: 'ludo-game-login-demo.firebasestorage.app',
    iosBundleId: 'com.example.ludoGameLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChiYTw5rKmP-ioG__X30GQgbAxwujxVvw',
    appId: '1:121984401432:ios:4739e656de7c58a92bc36d',
    messagingSenderId: '121984401432',
    projectId: 'ludo-game-login-demo',
    storageBucket: 'ludo-game-login-demo.firebasestorage.app',
    iosBundleId: 'com.example.ludoGameLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqcRWIfYLASO9aYmgbkKa6TafIQh07ec4',
    appId: '1:121984401432:web:5bab56e99a08f88e2bc36d',
    messagingSenderId: '121984401432',
    projectId: 'ludo-game-login-demo',
    authDomain: 'ludo-game-login-demo.firebaseapp.com',
    storageBucket: 'ludo-game-login-demo.firebasestorage.app',
    measurementId: 'G-EGFKQP350L',
  );
}
