// File generated by FlutterFire CLI placeholder.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1ekXAPLYW2GkR3lqfqDqrxC6MO0MnWg',
    appId: '1:803010359017:web:30930c743526fe9b72ca78',
    messagingSenderId: '803010359017',
    projectId: 'twitter-login-demo-c13a7',
    authDomain: 'twitter-login-demo-c13a7.firebaseapp.com',
    storageBucket: 'twitter-login-demo-c13a7.firebasestorage.app',
    measurementId: 'G-8SQRZ7844L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrP0ukv3Ajuc5_foG9DDyZ6Z5yKQCcSYo',
    appId: '1:803010359017:android:33c6864773575e8e72ca78',
    messagingSenderId: '803010359017',
    projectId: 'twitter-login-demo-c13a7',
    storageBucket: 'twitter-login-demo-c13a7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Uue0thJU083d-ExFISlSpKizfEFLo0s',
    appId: '1:803010359017:ios:faef1a67fc54427172ca78',
    messagingSenderId: '803010359017',
    projectId: 'twitter-login-demo-c13a7',
    storageBucket: 'twitter-login-demo-c13a7.firebasestorage.app',
    iosBundleId: 'com.example.twitterLogin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Uue0thJU083d-ExFISlSpKizfEFLo0s',
    appId: '1:803010359017:ios:faef1a67fc54427172ca78',
    messagingSenderId: '803010359017',
    projectId: 'twitter-login-demo-c13a7',
    storageBucket: 'twitter-login-demo-c13a7.firebasestorage.app',
    iosBundleId: 'com.example.twitterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1ekXAPLYW2GkR3lqfqDqrxC6MO0MnWg',
    appId: '1:803010359017:web:6a7259ae792104aa72ca78',
    messagingSenderId: '803010359017',
    projectId: 'twitter-login-demo-c13a7',
    authDomain: 'twitter-login-demo-c13a7.firebaseapp.com',
    storageBucket: 'twitter-login-demo-c13a7.firebasestorage.app',
    measurementId: 'G-LWLLFMF471',
  );
}
